Repository eps1lon/dom-accessibility-api, pull requests merged in 2020-07, with the labels that each got.

#324 Consider `<title>` for the name of its `<svg>` element.
  .changeset/nine-masks-begin.md
  sources/__tests__/accessible-name.js
  sources/accessible-name-and-description.ts
  sources/util.ts
Labels: enhancement

#332 test: Remove side-effects from helper utils
  sources/__tests__/accessible-description.js
  sources/__tests__/accessible-name.js
  sources/__tests__/helpers/test-utils.js
Labels: test

#334 test: Fix lint warnings
  .eslintrc
  sources/util.ts
Labels: test

#352 fix: Support native labels in IE 11
  .changeset/great-schools-listen.md
  sources/__tests__/accessible-name.js
  sources/accessible-name-and-description.ts
Labels: bug
