Repository eps1lon/dom-accessibility-api, pull requests merged in 2020-08, with the labels that each got.

#367 test: Mock IE 11 and Edge 14
  .eslintrc
  .gitignore
  .prettierignore
  azure-pipelines.yml
  package.json
  scripts/jest/jest-environment-jsdom-mock-edge14.js
  scripts/jest/jest-environment-jsdom-mock-ie11.js
  scripts/jest/jest.base.config.js
  scripts/jest/jest.ci.config.js
  scripts/jest/jest.config.js
  scripts/jest/jest.coverage.config.js
  scripts/jest/jest.jsdom.config.js
  scripts/jest/jest.mock-edge14.config.js
  scripts/jest/jest.mock-ie11.config.js
  sources/__tests__/accessible-name.js
Labels: test

#368 feat: Use localName when available
  .changeset/young-kangaroos-clap.md
  .eslintrc
  sources/accessible-name-and-description.ts
  sources/getRole.ts
  sources/util.ts
Labels: enhancement

#380 feat: Ignore before/after pseudo elements in JSDOM
  .changeset/witty-cycles-pay.md
  package.json
  scripts/jest/jest.base.config.js
  scripts/jest/jest.setup.js
  sources/__tests__/accessible-name.js
  sources/accessible-name-and-description.ts
  tests/cypress/support/index.js
  yarn.lock
Labels: bug

#394 fix: accessibility name when title is empty
  .changeset/gentle-lamps-perform.md
  sources/__tests__/accessible-name.js
  sources/accessible-name-and-description.ts
Labels: bug

#406 fix: consider value attribute before localized input type
  .changeset/empty-frogs-attend.md
  .eslintrc
  sources/__tests__/accessible-name.js
  sources/accessible-name-and-description.ts
  sources/util.ts
Labels: bug
