Repository eps1lon/dom-accessibility-api, pull requests merged in 2020-05, with the labels that each got.

#234 fix: Legend element as accessible name for Fielset element
  .changeset/pink-lizards-push.md
  sources/__tests__/accessible-name.js
  sources/accessible-name.ts
  sources/util.ts
Labels: bug

#235 test: lint js files
  .eslintrc
  package.json
  yarn.lock
Labels: test

#238 test: fix lint warnings
  .eslintrc
  package.json
  sources/accessible-name.ts
  sources/polyfills/SetLike.ts
  yarn.lock
Labels: test

#239 test(ci): Publish tarball as artifact
  azure-pipelines.yml
Labels: test

#240 feat: reduce transpilation helpers
  .changeset/poor-ways-film.md
  .eslintrc
  azure-pipelines.yml
  sources/accessible-name.ts
Labels: enhancement

#248 fix: Consider caption element of table
  .changeset/strange-hotels-build.md
  sources/__tests__/accessible-name.js
  sources/accessible-name.ts
  sources/util.ts
Labels: bug
